"""Add drought event type

Revision ID: 2f32b58a94b3
Revises: 9d8c29bc7461
Create Date: 2021-03-15 18:25:40.244357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f32b58a94b3"
down_revision = "9d8c29bc7461"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE eventtype ADD VALUE 'DROUGHT'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
