"""Audit trail

Revision ID: 3e59de044180
Revises: 9250aab85ae4
Create Date: 2021-01-19 09:31:36.906486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e59de044180"
down_revision = "9250aab85ae4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_trail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("admin_id", sa.Integer(), nullable=True),
        sa.Column("explanation", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["admin_id"], ["admins.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_trail_id"), "audit_trail", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_trail_id"), table_name="audit_trail")
    op.drop_table("audit_trail")
    # ### end Alembic commands ###
