"""Allow duplicated article URLs

Revision ID: 425cee5e4912
Revises: 57a1420579bc
Create Date: 2020-12-31 14:37:06.025173

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy.schema as sas


# revision identifiers, used by Alembic.
revision = "425cee5e4912"
down_revision = "57a1420579bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_articles_url", table_name="articles")
    op.drop_constraint("articles_pkey", table_name="articles")

    # op.add_column('articles', sa.Column('id', sa.Integer(), nullable=False))
    # op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)

    op.execute(sas.CreateSequence(sas.Sequence("articles_id_seq")))
    op.add_column(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False, server_default=sa.text("nextval('articles_id_seq'::regclass)")),
    )
    op.create_primary_key("ix_articles_id", "articles", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_articles_url", "articles", ["url"], unique=False)

    op.drop_index("ix_articles_id", table_name="articles")
    op.drop_column("articles", "id")
    # ### end Alembic commands ###
