"""Add volcano event type

Revision ID: 721a2fa8dacb
Revises: 3e59de044180
Create Date: 2021-02-04 13:47:07.553578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "721a2fa8dacb"
down_revision = "3e59de044180"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE eventtype ADD VALUE 'VOLCANO'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
