"""Added source field for article

Revision ID: 9d8c29bc7461
Revises: 721a2fa8dacb
Create Date: 2021-02-04 12:02:05.699175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d8c29bc7461"
down_revision = "721a2fa8dacb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("source", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "source")
    # ### end Alembic commands ###
