"""Add created datetime to events

Revision ID: a838278211a1
Revises: 88a33c410fe0
Create Date: 2021-01-14 15:12:43.232912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a838278211a1"
down_revision = "88a33c410fe0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("created", sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp())
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "created")
    # ### end Alembic commands ###
