"""Articles should be cascade-deleted

Revision ID: c2034cc81347
Revises: 90a22862149e
Create Date: 2020-12-30 10:42:45.926085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2034cc81347"
down_revision = "90a22862149e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("articles_owner_id_fkey", "articles", type_="foreignkey")
    op.create_foreign_key(None, "articles", "events", ["owner_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "articles", type_="foreignkey")
    op.create_foreign_key("articles_owner_id_fkey", "articles", "events", ["owner_id"], ["id"])
    # ### end Alembic commands ###
