"""Make articles image nullable; add missing index

Revision ID: c96a3e4d47aa
Revises: 425cee5e4912
Create Date: 2021-01-06 14:51:21.543302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c96a3e4d47aa"
down_revision = "425cee5e4912"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("articles", "image", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_articles_id2"), "articles", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_articles_id2"), table_name="articles")
    op.alter_column("articles", "image", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
