version: '2.1'
services:

  db:
    image: postgres:9.6-alpine
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME:-dtonapi}
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASS:-admin}
    ports:
      - "5432:5432"
    # network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -t 1 -q"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ${DB_DIR:-/tmp/dtonapidb/}:/var/lib/postgresql/data/
